#!/usr/bin/env node
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const source = join(here, 'linesentry-edge-flow.json');
const dist = join(root, 'packages', 'core', 'dist');

/**
 * Directory the certificate files are read from inside the Node-RED container.
 *
 * Overridden with CERT_DIR.
 */
const CERT_DIR = process.env.CERT_DIR ?? '/certs';

/**
 * Core modules the generated filter node is assembled from, in dependency
 * order.
 *
 * Each one imports only the modules before it, so concatenating them with the
 * module syntax removed produces a body Node-RED's function node can run.
 */
const BUNDLED = ['plant-config.js', 'predictor.js', 'edge.js'];

/** Driver appended to the bundle, holding the filter across messages. */
const DRIVER = `
const config = {
    deadband: DEADBAND,
    heartbeatMs: Number(env.get('HEARTBEAT_MS')) || HEARTBEAT_MS,
    errorBoundSigma: Number(env.get('ERROR_BOUND_SIGMA')) || DEFAULT_ERROR_BOUND_SIGMA,
    historyWindows: Number(env.get('PREDICTOR_HISTORY_WINDOWS')) || PREDICTOR_HISTORY_WINDOWS
};

let filter = context.get('filter');
if (!filter) {
    filter = createDualPredictionFilter(config);
    context.set('filter', filter);
}

const p = msg.payload;
const decision = filter.decide(p, Date.now());
const stats = context.get('stats') || { forwarded: 0, dropped: 0 };

if (!decision.forward) {
    stats.dropped++;
    context.set('stats', stats);
    return null;
}

stats.forwarded++;
context.set('stats', stats);
p.forward_reason = decision.reason;
if (decision.ext) p.ext = decision.ext;
node.status({ fill: 'green', shape: 'dot', text: 'fwd ' + stats.forwarded + ' / drop ' + stats.dropped });
return msg;
`;

/** Strips module syntax and registry wiring from one emitted core module. */
function inline(file) {
  return readFileSync(join(dist, file), 'utf8')
    .split('\n')
    .filter((line) => !/^import\s/.test(line))
    .filter((line) => !/^edgeFilterRegistry\.register\(/.test(line))
    .filter((line) => !/^\/\/# sourceMappingURL=/.test(line))
    .map((line) => line.replace(/^export (const|function|class|let|var) /, '$1 '))
    .filter((line) => !/^export /.test(line))
    .join('\n');
}

/**
 * Returns the generated body of the dual prediction filter node.
 *
 * The predictor and the filter are the compiled output of `packages/core`, so
 * the gateway and the detection service run one definition. See ./EDGE.md.
 */
function filterNodeBody() {
  const header = [
    '// Generated by edge/build-flows.mjs from packages/core. Do not edit.',
    `// Bundled: ${BUNDLED.join(', ')}`,
    '',
  ].join('\n');

  return `${header}${BUNDLED.map(inline).join('\n')}\n${DRIVER}`;
}

/** Compiles the generated body with the bindings Node-RED supplies. */
function compile(body, env) {
  const store = new Map();
  const context = { get: (k) => store.get(k), set: (k, v) => store.set(k, v) };
  const node = { send: () => undefined, status: () => undefined };
  const runtime = { get: (k) => env[k] };
  const compiled = new Function('msg', 'context', 'node', 'env', body);
  return (msg) => compiled(msg, context, node, runtime) ?? null;
}

/** Deterministic window stream used to check the bundle against the module. */
function fixture(count) {
  const START = 1789000000000;
  const windows = [];
  for (let i = 0; i < count; i++) {
    const jitter = ((i * 2654435761) % 1000) / 1000;
    const smoothed = Math.round((55 + i * 0.02 + 2 * Math.sin(i / 7) + jitter * 0.5) * 1000) / 1000;
    windows.push({
      edge_ts: START + i * 10000,
      window_start: START + i * 10000,
      window_end: START + (i + 1) * 10000,
      window: '10s',
      site_id: 'plant-01',
      line_id: 'line-A',
      machine_id: 'press-01',
      sensor_type: 'temperature',
      unit: 'C',
      count: 10,
      mean: smoothed,
      min: smoothed,
      max: smoothed,
      rms: smoothed,
      smoothed,
    });
  }
  return windows;
}

/**
 * Throws unless the generated body decides identically to the compiled module
 * over `fixture`.
 *
 * A stale bundle or a module the inliner mangled fails the build here rather
 * than silently running a different filter on the gateway than in the tests.
 */
async function verify(body) {
  if (/^\s*(import|export)\s/m.test(body)) throw new Error('generated body still has module syntax');
  if (/\brequire\s*\(/.test(body)) throw new Error('generated body calls require');

  const core = await import(join(dist, 'edge.js'));
  const errorBoundSigma = 1;
  const heartbeatMs = 300000;

  const reference = core.createDualPredictionFilter({
    deadband: core.DEADBAND,
    heartbeatMs,
    errorBoundSigma,
    historyWindows: core.PREDICTOR_HISTORY_WINDOWS,
  });

  const generated = compile(body, {
    HEARTBEAT_MS: String(heartbeatMs),
    ERROR_BOUND_SIGMA: String(errorBoundSigma),
  });

  let forwards = 0;
  for (const window of fixture(500)) {
    const expected = reference.decide({ ...window }, window.window_start);
    const actual = generated({ payload: { ...window } });

    if (expected.forward !== (actual !== null)) {
      throw new Error(`bundle disagreed on window ${window.window_start}`);
    }
    if (!expected.forward) continue;

    forwards++;
    const got = actual.payload;
    if (got.forward_reason !== expected.reason) {
      throw new Error(`bundle reason ${got.forward_reason} against ${expected.reason}`);
    }
    if (JSON.stringify(got.ext) !== JSON.stringify(expected.ext)) {
      throw new Error(`bundle ext differs at ${window.window_start}`);
    }
  }

  if (forwards < 5) throw new Error(`fixture produced only ${forwards} forwards`);
  return forwards;
}

/**
 * Returns the flow with its outbound node repointed at AWS IoT Core.
 *
 * Adds a TLS configuration and a second broker. The window, smoothing and
 * filter nodes are copied as they are, so one flow defines what the gateway
 * computes in both environments.
 */
function toAwsFlow(flow) {
  const rewritten = structuredClone(flow);

  rewritten.push({
    id: 'ls-iot-tls',
    type: 'tls-config',
    name: 'IoT Core device certificate',
    cert: join(CERT_DIR, 'device.pem.crt'),
    key: join(CERT_DIR, 'private.pem.key'),
    ca: join(CERT_DIR, 'AmazonRootCA1.pem'),
    certname: '',
    keyname: '',
    caname: '',
    servername: '',
    verifyservercert: true,
    alpnprotocol: 'x-amzn-mqtt-ca',
  });

  rewritten.push({
    id: 'ls-iot-broker',
    type: 'mqtt-broker',
    name: 'AWS IoT Core',
    broker: '${IOT_ENDPOINT}',
    port: '8883',
    clientid: '${IOT_CLIENT_ID}',
    autoConnect: true,
    usetls: true,
    tls: 'ls-iot-tls',
    protocolVersion: '4',
    keepalive: '60',
    cleansession: true,
    autoUnsubscribe: true,
    birthTopic: '',
    birthQos: '0',
    birthPayload: '',
    closeTopic: '',
    closeQos: '0',
    closePayload: '',
    willTopic: '',
    willQos: '0',
    willPayload: '',
    userProps: '',
    sessionExpiry: '',
  });

  const out = rewritten.find((node) => node.id === 'ls-mqtt-out');
  if (!out) throw new Error('flow has no ls-mqtt-out node to repoint');
  out.broker = 'ls-iot-broker';
  out.name = 'To AWS IoT Core';

  return rewritten;
}

/** Id the generated filter node takes in place of `ls-deadband`. */
const FILTER_NODE_ID = 'ls-dual-prediction';

/**
 * Returns the flow with its deadband node replaced by the generated filter.
 *
 * The node takes a new id and every wire into it is repointed, so nothing in
 * the generated flow is still named after the filter it replaced.
 */
function toDualPredictionFlow(flow, body) {
  const rewritten = structuredClone(flow);

  const filter = rewritten.find((node) => node.id === 'ls-deadband');
  if (!filter) throw new Error('flow has no ls-deadband node to replace');

  filter.id = FILTER_NODE_ID;
  filter.name = 'Dual prediction filter';
  filter.func = body;

  for (const node of rewritten) {
    if (!Array.isArray(node.wires)) continue;
    node.wires = node.wires.map((port) => port.map((target) => (target === 'ls-deadband' ? FILTER_NODE_ID : target)));
  }
  if (rewritten.some((node) => JSON.stringify(node.wires ?? []).includes('ls-deadband'))) {
    throw new Error('a wire still targets ls-deadband');
  }

  const tab = rewritten.find((node) => node.type === 'tab');
  if (tab) {
    tab.info =
      'Edge processing for LineSentry: window aggregation, EWMA smoothing and dual prediction ' +
      'filtering of raw sensor readings. A window is forwarded when it diverges from a least-squares ' +
      'prediction by more than ERROR_BOUND_SIGMA standard deviations, reaches a safety limit, or the ' +
      'heartbeat is due, and carries the model that governed the gap it closes.';
  }

  const comment = rewritten.find((node) => node.type === 'comment');
  if (comment) {
    comment.name =
      'Raw MQTT in -> 10 s window (mean/min/max/rms) -> EWMA -> dual prediction filter -> ' +
      'linesentry/edge/... . ERROR_BOUND_SIGMA and HEARTBEAT_MS set the bound and the heartbeat.';
  }

  return rewritten;
}

function write(name, flow) {
  const path = join(here, name);
  writeFileSync(path, `${JSON.stringify(flow, null, 4)}\n`);
  return path;
}

const flow = JSON.parse(readFileSync(source, 'utf8'));
const body = filterNodeBody();
const forwards = await verify(body);
const dual = toDualPredictionFlow(flow, body);

const written = [
  write('linesentry-edge-flow-aws.json', toAwsFlow(flow)),
  write('linesentry-edge-flow-dp.json', dual),
  write('linesentry-edge-flow-dp-aws.json', toAwsFlow(dual)),
];

console.log(`bundle verified against packages/core over ${forwards} forwards`);
for (const path of written) console.log(`wrote ${path}`);
