include classpath("application.conf")

node-address {
  protocol = http
  host = "elasticmq"
  port = 9324
  context-path = ""
}

rest-sqs {
  enabled = true
  bind-port = 9324
  bind-hostname = "0.0.0.0"
  sqs-limits = strict
}

queues {
  aggregation-q {
    defaultVisibilityTimeout = 60 seconds
    deadLettersQueue {
      name = "aggregation-dlq"
      maxReceiveCount = 3
    }
  }
  aggregation-dlq { }

  detection-q {
    defaultVisibilityTimeout = 60 seconds
    deadLettersQueue {
      name = "detection-dlq"
      maxReceiveCount = 3
    }
  }
  detection-dlq { }

  alerting-q {
    defaultVisibilityTimeout = 60 seconds
    deadLettersQueue {
      name = "alerting-dlq"
      maxReceiveCount = 3
    }
  }
  alerting-dlq { }
}
